### Basic Application Settings

### Server Settings
server:
  port: 8880

### Actuator Settings
management:
  endpoints:
    enabled-by-default: true
    health:
      show-details: "always"
#    logfile:
#      external-file: "batata.log"
    web:
      base-path: "/bactuator"
      exposure:
        include: "*"

### Data Source Settings
spring:
#  application:
#    name: batata-test
#  profiles:
#    active: dev

  datasource:
    jmx:
      enable: true
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password:
    url: "jdbc:h2:mem:testdb"

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
#Server:{server.port}/{spring.h2.console.path}   -> http:localhost:8880/h2
  h2:
    console:
      enabled: true
      path: "/h2"

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      fail-on-numbers-for-enums: true
    mapper:
      accept-case-insensitive-enums: false
#jpa sql logs
  jpa:
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

## Log Settings
#  logging.config=classpath:log4j2-spring.xml
logging:
  config: "log4j2-spring.xml"

### Endpoints
endpoint:
  url:
    actuator: "http://localhost:8880/bactuator"
    translate: "https://api.funtranslations.com"
    soap:
      country:
        info-wsdl: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL"
        info: "http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso"